server:
  port: 9527

spring:
  application:
    name: microservice-zuul-gateway



eureka:
  client:
    service-url.defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


# 配置路由规则
zuul:
  routes:
    mydept.serviceId: microservice-provider-dept
    mydept.path: /deptpath/**
  ignored-services: "*"   # 忽略所有的为服务通过真实的微服务名字访问
  prefix: /baihy  #为所有的微服务添加统一的前缀，此时一定要注意：必须要以斜杠开头