# 配置服务的信息
server:
  port: 8001
# 配置mybatis的信息
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

#配置数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hnzsfwq
    url: jdbc:mysql://127.0.0.1:3307/microservice-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource # 指定当前的数据源类型
  application:
    name: microservice-provider-dept

eureka:
  client:
    service-url.defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka # 配置eureka server的地址。
  instance:
    instance-id: microservice-provider-dept # 配置当前服务的服务名称
    prefer-ip-address: true # 访问路径可以显示ip地址



info:
  company: 河南中审科技有限公司
  projectName: @project.artifactId@
  version: @project.version@

