# 配置服务的信息
server:
  port: 8001
# 配置mybatis的信息
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

#配置数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3308/microservice-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource # 指定当前的数据源类型
  application:
    name: microservice-provider
